# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "03f9285a-2b8f-4daa-9873-549325797fb3",
# META       "default_lakehouse_name": "Dev_Lakehouse",
# META       "default_lakehouse_workspace_id": "6cfe7d37-f6e1-4461-8c01-6c70d981e257",
# META       "known_lakehouses": [
# META         {
# META           "id": "03f9285a-2b8f-4daa-9873-549325797fb3"
# META         }
# META       ]
# META     }
# META   }
# META }

# MARKDOWN ********************

# # 02 — Data Transformation (Silver Layer)
# **Generated by GitHub Copilot Agent Mode**
# # MAGIC
# Transforms Bronze tables into Silver-layer curated datasets:
# - Standardizes dates and currencies
# - Calculates derived columns (depreciation, variance)
# - Creates regional aggregations for RLS demo

# CELL ********************

from pyspark.sql.functions import (
    col, to_date, year, month, datediff, current_date,
    round as spark_round, when, lit, sum as spark_sum,
    avg, count, current_timestamp, concat_ws
)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## Silver: Fixed Assets with Calculated Depreciation

# CELL ********************

bronze_assets = spark.table("bronze_fixed_assets")

silver_assets = (
    bronze_assets
    .withColumn("acquisition_date", to_date(col("acquisition_date"), "yyyy-MM-dd"))
    .withColumn("age_days", datediff(current_date(), col("acquisition_date")))
    .withColumn("age_years", spark_round(col("age_days") / 365.25, 1))
    .withColumn(
        "annual_depreciation",
        when(col("useful_life_years") > 0,
             spark_round(col("acquisition_cost") / col("useful_life_years"), 2))
        .otherwise(0)
    )
    .withColumn(
        "accumulated_depreciation",
        spark_round(
            when(col("age_years") <= col("useful_life_years"),
                 col("annual_depreciation") * col("age_years"))
            .otherwise(col("acquisition_cost") - lit(1)),  # Residual value of 1
            2
        )
    )
    .withColumn(
        "net_book_value",
        spark_round(col("acquisition_cost") - col("accumulated_depreciation"), 2)
    )
    .withColumn("_transformed_at", current_timestamp())
    .drop("_ingested_at", "_source_file")
)

silver_assets.write.format("delta").mode("overwrite").saveAsTable("silver_fixed_assets")
print(f"✅ silver_fixed_assets: {silver_assets.count()} rows")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## Silver: Budget vs Actuals with Variance Analysis

# CELL ********************

from pyspark.sql.functions import abs as spark_abs

bronze_budgets = spark.table("bronze_regional_budgets")

silver_budgets = (
    bronze_budgets
    .withColumn("variance", spark_round(col("actual_amount") - col("budget_amount"), 2))
    .withColumn(
        "variance_pct",
        spark_round(
            when(col("budget_amount") != 0,
                 (col("actual_amount") - col("budget_amount")) / col("budget_amount") * 100)
            .otherwise(0),
            1
        )
    )
    .withColumn(
        "forecast_accuracy_pct",
        spark_round(
            when(col("forecast_amount") != 0,
                 (1 - spark_abs(col("actual_amount") - col("forecast_amount")) / col("forecast_amount")) * 100)
            .otherwise(0),
            1
        )
    )
    .withColumn(
        "status",
        when(col("variance_pct") > 10, "Over Budget")
        .when(col("variance_pct") < -10, "Under Budget")
        .otherwise("On Track")
    )
    .withColumn("_transformed_at", current_timestamp())
    .drop("_ingested_at", "_source_file")
)

silver_budgets.write.format("delta").mode("overwrite").saveAsTable("silver_regional_budgets")
print(f"✅ silver_regional_budgets: {silver_budgets.count()} rows")


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## Silver: Employee Region Mapping (for RLS)

# CELL ********************

# Fix: No 'is_manager' column exists. Use heuristics to determine 'security_group'.
# If 'department' contains 'Manager' (case-insensitive), treat as manager. Otherwise, viewer.
# 'role' column is not a manager/employee indicator, so use department string matching.
from pyspark.sql.functions import lower

bronze_employees = spark.table("bronze_employee_regions")

silver_employees = (
    bronze_employees
    .withColumn(
        "security_group",
        when(lower(col("department")).contains("manager"),
             concat_ws("-", lit("Manager"), col("region")))
        .otherwise(concat_ws("-", lit("Viewer"), col("region")))
    )
    .withColumn("_transformed_at", current_timestamp())
    .drop("_ingested_at", "_source_file")
)

silver_employees.write.format("delta").mode("overwrite").saveAsTable("silver_employee_regions")
print(f"✅ silver_employee_regions: {silver_employees.count()} rows")


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## Regional Aggregation Summary

# CELL ********************

regional_summary = (
    silver_assets
    .groupBy("region")
    .agg(
        count("*").alias("total_assets"),
        spark_round(spark_sum("acquisition_cost"), 0).alias("total_acquisition_cost"),
        spark_round(spark_sum("net_book_value"), 0).alias("total_net_book_value"),
        spark_round(avg("age_years"), 1).alias("avg_asset_age_years"),
    )
    .orderBy("region")
)

regional_summary.write.format("delta").mode("overwrite").saveAsTable("silver_regional_asset_summary")
print(f"✅ silver_regional_asset_summary:")
regional_summary.show(truncate=False)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
