# Databricks notebook source
# MAGIC %md
# MAGIC # 01 — Data Ingestion (Bronze Layer)
# MAGIC **Generated by GitHub Copilot Agent Mode**
# MAGIC
# MAGIC Loads CSV files from the lakehouse Files section into Delta tables.
# MAGIC Run this notebook after uploading the sample-data CSVs to your lakehouse.

# COMMAND ----------

from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql.functions import current_timestamp, lit, input_file_name

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configuration

# COMMAND ----------

LAKEHOUSE_PATH = "Files/sample-data"  # Path relative to lakehouse root
TABLES_PATH = "Tables"

DATASETS = {
    "fixed_assets": {
        "file": "fixed_assets.csv",
        "schema": StructType([
            StructField("asset_id", StringType(), False),
            StructField("asset_name", StringType(), False),
            StructField("category", StringType(), True),
            StructField("region", StringType(), True),
            StructField("country", StringType(), True),
            StructField("acquisition_date", StringType(), True),
            StructField("acquisition_cost", DoubleType(), True),
            StructField("current_value", DoubleType(), True),
            StructField("depreciation_method", StringType(), True),
            StructField("useful_life_years", IntegerType(), True),
            StructField("status", StringType(), True),
        ]),
    },
    "regional_budgets": {
        "file": "regional_budgets.csv",
        "schema": StructType([
            StructField("budget_id", StringType(), False),
            StructField("region", StringType(), False),
            StructField("department", StringType(), True),
            StructField("fiscal_year", IntegerType(), True),
            StructField("quarter", StringType(), True),
            StructField("budget_amount", DoubleType(), True),
            StructField("actual_amount", DoubleType(), True),
            StructField("forecast_amount", DoubleType(), True),
            StructField("currency", StringType(), True),
        ]),
    },
    "employee_regions": {
        "file": "employee_regions.csv",
        "schema": StructType([
            StructField("employee_id", StringType(), False),
            StructField("email", StringType(), False),
            StructField("display_name", StringType(), True),
            StructField("region", StringType(), True),
            StructField("country", StringType(), True),
            StructField("role", StringType(), True),
            StructField("department", StringType(), True),
            StructField("is_manager", BooleanType(), True),
        ]),
    },
}

# COMMAND ----------

# MAGIC %md
# MAGIC ## Ingest CSVs into Bronze Delta Tables

# COMMAND ----------

for table_name, config in DATASETS.items():
    print(f"📥 Ingesting {table_name}...")

    df = (
        spark.read
        .option("header", "true")
        .schema(config["schema"])
        .csv(f"{LAKEHOUSE_PATH}/{config['file']}")
    )

    # Add ingestion metadata
    df = (
        df
        .withColumn("_ingested_at", current_timestamp())
        .withColumn("_source_file", lit(config["file"]))
    )

    # Write as Delta table (overwrite for demo; use merge/append in production)
    (
        df.write
        .format("delta")
        .mode("overwrite")
        .option("overwriteSchema", "true")
        .saveAsTable(f"bronze_{table_name}")
    )

    row_count = spark.table(f"bronze_{table_name}").count()
    print(f"   ✅ bronze_{table_name}: {row_count} rows loaded")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Verify Tables

# COMMAND ----------

for table_name in DATASETS:
    df = spark.table(f"bronze_{table_name}")
    print(f"\n📊 bronze_{table_name} ({df.count()} rows):")
    df.show(3, truncate=False)
