# Databricks notebook source
# MAGIC %md
# MAGIC # 02 — Data Transformation (Silver Layer)
# MAGIC **Generated by GitHub Copilot Agent Mode**
# MAGIC
# MAGIC Transforms Bronze tables into Silver-layer curated datasets:
# MAGIC - Standardizes dates and currencies
# MAGIC - Calculates derived columns (depreciation, variance)
# MAGIC - Creates regional aggregations for RLS demo

# COMMAND ----------

from pyspark.sql.functions import (
    col, to_date, year, month, datediff, current_date,
    round as spark_round, when, lit, sum as spark_sum,
    avg, count, current_timestamp, concat_ws
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Silver: Fixed Assets with Calculated Depreciation

# COMMAND ----------

bronze_assets = spark.table("bronze_fixed_assets")

silver_assets = (
    bronze_assets
    .withColumn("acquisition_date", to_date(col("acquisition_date"), "yyyy-MM-dd"))
    .withColumn("age_days", datediff(current_date(), col("acquisition_date")))
    .withColumn("age_years", spark_round(col("age_days") / 365.25, 1))
    .withColumn(
        "annual_depreciation",
        when(col("useful_life_years") > 0,
             spark_round(col("acquisition_cost") / col("useful_life_years"), 2))
        .otherwise(0)
    )
    .withColumn(
        "accumulated_depreciation",
        spark_round(
            when(col("age_years") <= col("useful_life_years"),
                 col("annual_depreciation") * col("age_years"))
            .otherwise(col("acquisition_cost") - lit(1)),  # Residual value of 1
            2
        )
    )
    .withColumn(
        "net_book_value",
        spark_round(col("acquisition_cost") - col("accumulated_depreciation"), 2)
    )
    .withColumn("_transformed_at", current_timestamp())
    .drop("_ingested_at", "_source_file")
)

silver_assets.write.format("delta").mode("overwrite").saveAsTable("silver_fixed_assets")
print(f"✅ silver_fixed_assets: {silver_assets.count()} rows")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Silver: Budget vs Actuals with Variance Analysis

# COMMAND ----------

bronze_budgets = spark.table("bronze_regional_budgets")

silver_budgets = (
    bronze_budgets
    .withColumn("variance", spark_round(col("actual_amount") - col("budget_amount"), 2))
    .withColumn(
        "variance_pct",
        spark_round(
            when(col("budget_amount") != 0,
                 (col("actual_amount") - col("budget_amount")) / col("budget_amount") * 100)
            .otherwise(0),
            1
        )
    )
    .withColumn(
        "forecast_accuracy_pct",
        spark_round(
            when(col("forecast_amount") != 0,
                 (1 - abs(col("actual_amount") - col("forecast_amount")) / col("forecast_amount")) * 100)
            .otherwise(0),
            1
        )
    )
    .withColumn(
        "status",
        when(col("variance_pct") > 10, "Over Budget")
        .when(col("variance_pct") < -10, "Under Budget")
        .otherwise("On Track")
    )
    .withColumn("_transformed_at", current_timestamp())
    .drop("_ingested_at", "_source_file")
)

silver_budgets.write.format("delta").mode("overwrite").saveAsTable("silver_regional_budgets")
print(f"✅ silver_regional_budgets: {silver_budgets.count()} rows")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Silver: Employee Region Mapping (for RLS)

# COMMAND ----------

bronze_employees = spark.table("bronze_employee_regions")

silver_employees = (
    bronze_employees
    .withColumn(
        "security_group",
        when(col("is_manager") == True,
             concat_ws("-", lit("Manager"), col("region")))
        .otherwise(concat_ws("-", lit("Viewer"), col("region")))
    )
    .withColumn("_transformed_at", current_timestamp())
    .drop("_ingested_at", "_source_file")
)

silver_employees.write.format("delta").mode("overwrite").saveAsTable("silver_employee_regions")
print(f"✅ silver_employee_regions: {silver_employees.count()} rows")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Regional Aggregation Summary

# COMMAND ----------

regional_summary = (
    silver_assets
    .groupBy("region")
    .agg(
        count("*").alias("total_assets"),
        spark_round(spark_sum("acquisition_cost"), 0).alias("total_acquisition_cost"),
        spark_round(spark_sum("net_book_value"), 0).alias("total_net_book_value"),
        spark_round(avg("age_years"), 1).alias("avg_asset_age_years"),
    )
    .orderBy("region")
)

regional_summary.write.format("delta").mode("overwrite").saveAsTable("silver_regional_asset_summary")
print(f"✅ silver_regional_asset_summary:")
regional_summary.show(truncate=False)
