# Databricks notebook source
# MAGIC %md
# MAGIC # 03 — Data Quality Checks
# MAGIC **Generated by GitHub Copilot Agent Mode**
# MAGIC
# MAGIC Automated data quality validation for Silver-layer tables.
# MAGIC Fails the notebook if any critical checks don't pass.

# COMMAND ----------

from pyspark.sql.functions import col, count, when, isnan, isnull, min, max

# COMMAND ----------

class DataQualityChecker:
    """Simple DQ framework for Fabric notebooks."""

    def __init__(self):
        self.results = []

    def check(self, name, table, condition, severity="critical"):
        """Run a DQ check. condition should be a boolean (True = pass)."""
        status = "✅ PASS" if condition else ("❌ FAIL" if severity == "critical" else "⚠️ WARN")
        self.results.append({
            "check": name,
            "table": table,
            "status": status,
            "severity": severity,
            "passed": condition,
        })
        print(f"  {status} | {table} | {name}")

    def check_not_null(self, table_name, column):
        df = spark.table(table_name)
        null_count = df.filter(col(column).isNull()).count()
        self.check(
            f"{column} has no nulls",
            table_name,
            null_count == 0,
        )

    def check_row_count(self, table_name, min_rows=1):
        df = spark.table(table_name)
        row_count = df.count()
        self.check(
            f"Row count >= {min_rows} (actual: {row_count})",
            table_name,
            row_count >= min_rows,
        )

    def check_no_duplicates(self, table_name, key_columns):
        df = spark.table(table_name)
        total = df.count()
        distinct = df.select(key_columns).distinct().count()
        self.check(
            f"No duplicate keys on {key_columns}",
            table_name,
            total == distinct,
        )

    def check_values_in_set(self, table_name, column, valid_values):
        df = spark.table(table_name)
        invalid = df.filter(~col(column).isin(valid_values)).count()
        self.check(
            f"{column} values are valid (invalid: {invalid})",
            table_name,
            invalid == 0,
            severity="warning",
        )

    def check_numeric_range(self, table_name, column, min_val=None, max_val=None):
        df = spark.table(table_name)
        stats = df.select(min(column).alias("min"), max(column).alias("max")).first()
        conditions = []
        if min_val is not None:
            conditions.append(stats["min"] >= min_val)
        if max_val is not None:
            conditions.append(stats["max"] <= max_val)
        self.check(
            f"{column} in range [{min_val}, {max_val}] (actual: [{stats['min']}, {stats['max']}])",
            table_name,
            all(conditions),
        )

    def summary(self):
        passed = sum(1 for r in self.results if r["passed"])
        failed = sum(1 for r in self.results if not r["passed"] and r["severity"] == "critical")
        warnings = sum(1 for r in self.results if not r["passed"] and r["severity"] == "warning")
        total = len(self.results)
        print(f"\n{'='*60}")
        print(f"Data Quality Summary: {passed}/{total} passed, {failed} failed, {warnings} warnings")
        print(f"{'='*60}")
        if failed > 0:
            print("❌ CRITICAL FAILURES DETECTED — pipeline should not proceed")
            raise Exception(f"Data quality check failed: {failed} critical failures")
        elif warnings > 0:
            print("⚠️ Warnings detected but no critical failures — proceeding")
        else:
            print("✅ All checks passed")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Run Quality Checks

# COMMAND ----------

dq = DataQualityChecker()

# ── Fixed Assets ──
print("📋 Fixed Assets Checks:")
dq.check_row_count("silver_fixed_assets", min_rows=10)
dq.check_not_null("silver_fixed_assets", "asset_id")
dq.check_not_null("silver_fixed_assets", "region")
dq.check_no_duplicates("silver_fixed_assets", ["asset_id"])
dq.check_numeric_range("silver_fixed_assets", "acquisition_cost", min_val=0)
dq.check_numeric_range("silver_fixed_assets", "net_book_value", min_val=0)
dq.check_values_in_set("silver_fixed_assets", "status",
                        ["Active", "Disposed", "Under Maintenance", "Retired"])
dq.check_values_in_set("silver_fixed_assets", "region",
                        ["NorthEurope", "WestEurope", "APAC", "NorthAmerica", "MiddleEast"])

# ── Regional Budgets ──
print("\n📋 Regional Budgets Checks:")
dq.check_row_count("silver_regional_budgets", min_rows=10)
dq.check_not_null("silver_regional_budgets", "budget_id")
dq.check_not_null("silver_regional_budgets", "region")
dq.check_no_duplicates("silver_regional_budgets", ["budget_id"])
dq.check_numeric_range("silver_regional_budgets", "budget_amount", min_val=0)

# ── Employee Regions ──
print("\n📋 Employee Regions Checks:")
dq.check_row_count("silver_employee_regions", min_rows=5)
dq.check_not_null("silver_employee_regions", "employee_id")
dq.check_not_null("silver_employee_regions", "email")
dq.check_no_duplicates("silver_employee_regions", ["employee_id"])

# ── Summary ──
dq.summary()
