<#
.SYNOPSIS
    Check Git sync status across all Fabric workspaces.
    Generated by GitHub Copilot Agent Mode.

.DESCRIPTION
    Connects to the Fabric REST API and reports the Git sync status
    for each workspace. Identifies items that are stuck, in conflict,
    or out of sync.

.EXAMPLE
    .\Check-GitSyncStatus.ps1 -WorkspaceIds @("guid1", "guid2")
#>

param(
    [Parameter(Mandatory = $false)]
    [string[]]$WorkspaceIds = @(),

    [Parameter(Mandatory = $false)]
    [string]$OutputFormat = "Table"  # Table, JSON, or CSV
)

$ErrorActionPreference = "Stop"

# ── Authentication ──
Write-Host "🔑 Authenticating..." -ForegroundColor Cyan
$token = (Get-AzAccessToken -ResourceUrl "https://api.fabric.microsoft.com").Token
$headers = @{ Authorization = "Bearer $token" }
$apiBase = "https://api.fabric.microsoft.com/v1"

# ── Get workspaces if not specified ──
if ($WorkspaceIds.Count -eq 0) {
    Write-Host "📋 Fetching all workspaces..." -ForegroundColor Cyan
    $workspaces = Invoke-RestMethod -Uri "$apiBase/workspaces" -Headers $headers
    $WorkspaceIds = $workspaces.value | Where-Object { $_.type -eq "Workspace" } | Select-Object -ExpandProperty id
}

# ── Check each workspace ──
$results = @()

foreach ($wsId in $WorkspaceIds) {
    try {
        # Get workspace details
        $ws = Invoke-RestMethod -Uri "$apiBase/workspaces/$wsId" -Headers $headers

        # Check Git connection
        $conn = Invoke-RestMethod -Uri "$apiBase/workspaces/$wsId/git/connection" -Headers $headers -ErrorAction SilentlyContinue

        if (-not $conn.gitProviderDetails) {
            $results += [PSCustomObject]@{
                Workspace   = $ws.displayName
                GitStatus   = "Not Connected"
                Branch      = "-"
                InSync      = "-"
                Changes     = 0
                Conflicts   = 0
                Health      = "⚪ N/A"
            }
            continue
        }

        # Get sync status
        $status = Invoke-RestMethod -Uri "$apiBase/workspaces/$wsId/git/status" -Headers $headers

        $changes = ($status.changes | Measure-Object).Count
        $conflicts = ($status.changes | Where-Object { $_.conflictType -and $_.conflictType -ne "None" } | Measure-Object).Count
        $inSync = $status.remoteCommitHash -eq $status.workspaceHead

        # Determine health
        $health = if ($conflicts -gt 0) { "🔴 Critical" }
                  elseif (-not $inSync) { "🟡 Warning" }
                  else { "🟢 Healthy" }

        $results += [PSCustomObject]@{
            Workspace   = $ws.displayName
            GitStatus   = "Connected"
            Branch      = $conn.gitProviderDetails.branch
            InSync      = $inSync
            Changes     = $changes
            Conflicts   = $conflicts
            Health      = $health
        }

        # If there are stuck items, list them
        if ($changes -gt 0) {
            foreach ($change in $status.changes) {
                Write-Host "  ⚠️ $($ws.displayName): $($change.itemName) ($($change.itemType)) - $($change.conflictType)" -ForegroundColor Yellow
            }
        }
    }
    catch {
        $results += [PSCustomObject]@{
            Workspace   = $wsId
            GitStatus   = "Error"
            Branch      = "-"
            InSync      = "-"
            Changes     = 0
            Conflicts   = 0
            Health      = "🔴 Error: $($_.Exception.Message)"
        }
    }
}

# ── Output ──
Write-Host "`n📊 Git Sync Status Report" -ForegroundColor Cyan
Write-Host ("=" * 60)

switch ($OutputFormat) {
    "JSON" { $results | ConvertTo-Json -Depth 5 }
    "CSV"  { $results | Export-Csv -Path "sync-status-report.csv" -NoTypeInformation; Write-Host "Exported to sync-status-report.csv" }
    default { $results | Format-Table -AutoSize }
}

# Summary
$healthy = ($results | Where-Object { $_.Health -like "*Healthy*" } | Measure-Object).Count
$warnings = ($results | Where-Object { $_.Health -like "*Warning*" } | Measure-Object).Count
$critical = ($results | Where-Object { $_.Health -like "*Critical*" -or $_.Health -like "*Error*" } | Measure-Object).Count

Write-Host "`n🟢 Healthy: $healthy | 🟡 Warnings: $warnings | 🔴 Critical: $critical" -ForegroundColor White
