<#
.SYNOPSIS
    Fan-out deployment from Dev to multiple regional workspaces.
    Generated by GitHub Copilot Agent Mode.

.DESCRIPTION
    Triggers Fabric Deployment Pipeline deployments to multiple regions in parallel.
    Uses PowerShell jobs for concurrent execution.

.EXAMPLE
    .\Deploy-FanOut.ps1 -TargetStage "qa"
#>

param(
    [Parameter(Mandatory = $false)]
    [ValidateSet("qa", "prod")]
    [string]$TargetStage = "qa"
)

$ErrorActionPreference = "Stop"

# ── Configuration ──
$pipelines = @(
    @{ Region = "NorthEurope"; PipelineId = "PIPELINE-GUID-NORTH-EUROPE" }
    @{ Region = "WestEurope";  PipelineId = "PIPELINE-GUID-WEST-EUROPE" }
    @{ Region = "EastUS";      PipelineId = "PIPELINE-GUID-EAST-US" }
)

$stageOrder = if ($TargetStage -eq "prod") { 1 } else { 0 }

# ── Authentication ──
Write-Host "🔑 Authenticating..." -ForegroundColor Cyan
$token = (Get-AzAccessToken -ResourceUrl "https://api.fabric.microsoft.com").Token
$headers = @{ Authorization = "Bearer $token"; "Content-Type" = "application/json" }
$apiBase = "https://api.fabric.microsoft.com/v1"

# ── Deploy to all regions in parallel ──
Write-Host "`n🚀 Deploying to $($pipelines.Count) regions ($TargetStage)..." -ForegroundColor Cyan

$jobs = @()

foreach ($pipeline in $pipelines) {
    $jobs += Start-Job -ScriptBlock {
        param($ApiBase, $PipelineId, $Region, $StageOrder, $Headers)

        $body = @{
            sourceStageOrder    = $StageOrder
            isBackwardDeployment = $false
            newDeployment       = $false
            note                = "Fan-out deploy from PowerShell - $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
        } | ConvertTo-Json

        try {
            $result = Invoke-RestMethod `
                -Uri "$ApiBase/deploymentPipelines/$PipelineId/deploy" `
                -Method POST `
                -Body $body `
                -Headers $Headers

            return @{ Region = $Region; Status = "Success"; Message = "Deployment triggered" }
        }
        catch {
            return @{ Region = $Region; Status = "Failed"; Message = $_.Exception.Message }
        }
    } -ArgumentList $apiBase, $pipeline.PipelineId, $pipeline.Region, $stageOrder, $headers
}

# ── Wait for all deployments ──
Write-Host "⏳ Waiting for all deployments to complete..." -ForegroundColor Cyan
$results = $jobs | Wait-Job | Receive-Job
$jobs | Remove-Job

# ── Report results ──
Write-Host "`n📊 Deployment Results:" -ForegroundColor Cyan
Write-Host ("=" * 50)

foreach ($result in $results) {
    $icon = if ($result.Status -eq "Success") { "✅" } else { "❌" }
    Write-Host "$icon $($result.Region): $($result.Status) - $($result.Message)"
}

$successCount = ($results | Where-Object { $_.Status -eq "Success" } | Measure-Object).Count
$failCount = ($results | Where-Object { $_.Status -eq "Failed" } | Measure-Object).Count

Write-Host "`n✅ Success: $successCount | ❌ Failed: $failCount"

if ($failCount -gt 0) {
    Write-Host "⚠️ Some deployments failed. Check the output above." -ForegroundColor Yellow
    exit 1
}
