<#
.SYNOPSIS
    Force a Fabric workspace to match its Git branch.
    Generated by GitHub Copilot Agent Mode.

.DESCRIPTION
    Discards all local workspace changes and syncs from Git.
    Use this to recover from accidental changes in the collaboration workspace.

.EXAMPLE
    .\Force-SyncFromGit.ps1 -WorkspaceId "your-workspace-guid"
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$WorkspaceId,

    [Parameter(Mandatory = $false)]
    [string]$ConflictResolution = "Workspace"  # "Workspace" keeps Git version; "Remote" keeps workspace version
)

$ErrorActionPreference = "Stop"

# ── Authentication ──
Write-Host "🔑 Authenticating..." -ForegroundColor Cyan
$token = (Get-AzAccessToken -ResourceUrl "https://api.fabric.microsoft.com").Token
$headers = @{ Authorization = "Bearer $token"; "Content-Type" = "application/json" }
$apiBase = "https://api.fabric.microsoft.com/v1"

# ── Step 1: Get current status ──
Write-Host "`n📊 Step 1: Checking current Git sync status..." -ForegroundColor Cyan
$status = Invoke-RestMethod `
    -Uri "$apiBase/workspaces/$WorkspaceId/git/status" `
    -Headers $headers

Write-Host "  Remote commit:  $($status.remoteCommitHash)"
Write-Host "  Workspace head: $($status.workspaceHead)"
$changeCount = ($status.changes | Measure-Object).Count
Write-Host "  Pending changes: $changeCount"

if ($status.remoteCommitHash -eq $status.workspaceHead -and $changeCount -eq 0) {
    Write-Host "`n✅ Workspace is already in sync with Git. Nothing to do." -ForegroundColor Green
    exit 0
}

# ── Step 2: Show what will be overwritten ──
Write-Host "`n📋 Step 2: Items that will be affected:" -ForegroundColor Yellow
foreach ($change in $status.changes) {
    $icon = switch ($change.conflictType) {
        "None"      { "📝" }
        "Conflict"  { "⚠️" }
        default     { "❓" }
    }
    Write-Host "  $icon $($change.itemName) ($($change.itemType)) - $($change.changeType)"
}

# ── Step 3: Force sync from Git ──
Write-Host "`n🔄 Step 3: Syncing workspace from Git (resolution: $ConflictResolution)..." -ForegroundColor Cyan
$body = @{
    remoteCommitHash   = $status.remoteCommitHash
    conflictResolution = @{ conflictResolutionType = $ConflictResolution }
    options            = @{ allowOverrideItems = $true }
} | ConvertTo-Json -Depth 5

try {
    $result = Invoke-RestMethod `
        -Uri "$apiBase/workspaces/$WorkspaceId/git/updateFromGit" `
        -Method POST `
        -Body $body `
        -Headers $headers

    Write-Host "`n✅ Workspace synced successfully from Git!" -ForegroundColor Green
}
catch {
    Write-Host "`n❌ Sync failed: $($_.Exception.Message)" -ForegroundColor Red
    throw
}

# ── Step 4: Verify ──
Write-Host "`n🔍 Step 4: Verifying sync..." -ForegroundColor Cyan
Start-Sleep -Seconds 5

$newStatus = Invoke-RestMethod `
    -Uri "$apiBase/workspaces/$WorkspaceId/git/status" `
    -Headers $headers

if ($newStatus.remoteCommitHash -eq $newStatus.workspaceHead) {
    Write-Host "✅ Verified: workspace now matches Git" -ForegroundColor Green
} else {
    Write-Host "⚠️ Sync may still be processing. Check again in a moment." -ForegroundColor Yellow
}
