<#
.SYNOPSIS
    Extract direct download URLs for images stored in SharePoint.
    Generated by GitHub Copilot Agent Mode.

.DESCRIPTION
    Uses Microsoft Graph API to get direct download URLs for image files
    in a SharePoint document library. These URLs can be used in Power BI
    with the "Image URL" data category.

.EXAMPLE
    .\Get-SharePointImageUrls.ps1 -SiteId "site-guid" -LibraryName "Asset Photos"
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$SiteId,

    [Parameter(Mandatory = $false)]
    [string]$LibraryName = "Documents",

    [Parameter(Mandatory = $false)]
    [string]$OutputPath = "sharepoint_image_urls.csv"
)

$ErrorActionPreference = "Stop"

# ── Authentication ──
Write-Host "🔑 Authenticating..." -ForegroundColor Cyan
$token = (Get-AzAccessToken -ResourceUrl "https://graph.microsoft.com").Token
$headers = @{ Authorization = "Bearer $token" }
$graphBase = "https://graph.microsoft.com/v1.0"

# ── Get drive (document library) ──
Write-Host "📂 Finding library '$LibraryName'..." -ForegroundColor Cyan
$drives = Invoke-RestMethod `
    -Uri "$graphBase/sites/$SiteId/drives" `
    -Headers $headers

$drive = $drives.value | Where-Object { $_.name -eq $LibraryName } | Select-Object -First 1

if (-not $drive) {
    Write-Host "❌ Library '$LibraryName' not found." -ForegroundColor Red
    Write-Host "Available libraries:"
    $drives.value | ForEach-Object { Write-Host "  - $($_.name)" }
    exit 1
}

Write-Host "  Drive ID: $($drive.id)"

# ── Get all image files ──
Write-Host "🖼️ Scanning for image files..." -ForegroundColor Cyan
$imageExtensions = @(".jpg", ".jpeg", ".png", ".gif", ".bmp", ".svg", ".webp")

function Get-ImagesRecursive {
    param($DriveId, $FolderId, $Path)

    $uri = if ($FolderId) {
        "$graphBase/drives/$DriveId/items/$FolderId/children"
    } else {
        "$graphBase/drives/$DriveId/root/children"
    }

    $items = Invoke-RestMethod -Uri $uri -Headers $headers
    $images = @()

    foreach ($item in $items.value) {
        $currentPath = if ($Path) { "$Path/$($item.name)" } else { $item.name }

        if ($item.folder) {
            # Recurse into subfolders
            $images += Get-ImagesRecursive -DriveId $DriveId -FolderId $item.id -Path $currentPath
        }
        elseif ($imageExtensions -contains [System.IO.Path]::GetExtension($item.name).ToLower()) {
            # Get the direct download URL
            $itemDetail = Invoke-RestMethod `
                -Uri "$graphBase/drives/$DriveId/items/$($item.id)" `
                -Headers $headers

            $downloadUrl = $itemDetail.'@microsoft.graph.downloadUrl'

            $images += [PSCustomObject]@{
                FileName    = $item.name
                Path        = $currentPath
                ImageUrl    = $downloadUrl
                FileSize    = $item.size
                ModifiedAt  = $item.lastModifiedDateTime
                ItemId      = $item.id
            }

            Write-Host "  ✅ $currentPath"
        }
    }

    return $images
}

$images = Get-ImagesRecursive -DriveId $drive.id -FolderId $null -Path ""

# ── Export results ──
Write-Host "`n📊 Found $($images.Count) images" -ForegroundColor Cyan

if ($images.Count -gt 0) {
    $images | Export-Csv -Path $OutputPath -NoTypeInformation
    Write-Host "✅ Exported to $OutputPath" -ForegroundColor Green
    Write-Host "`nNext steps:"
    Write-Host "  1. Load $OutputPath into your lakehouse"
    Write-Host "  2. In Power BI, set the ImageUrl column's Data Category to 'Image URL'"
    Write-Host "  3. Use the column in Table, Matrix, or Card visuals"
} else {
    Write-Host "⚠️ No images found in '$LibraryName'" -ForegroundColor Yellow
}
