<#
.SYNOPSIS
    Rebind a Power BI report to a different semantic model.
    Generated by GitHub Copilot Agent Mode.

.DESCRIPTION
    Uses the Power BI REST API to change a report's data source binding
    WITHOUT recreating the report. Preserves all report layouts and visuals.

.EXAMPLE
    .\Rebind-Report.ps1 -WorkspaceId "ws-guid" -ReportId "report-guid" -TargetDatasetId "model-guid"
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$WorkspaceId,

    [Parameter(Mandatory = $true)]
    [string]$ReportId,

    [Parameter(Mandatory = $true)]
    [string]$TargetDatasetId
)

$ErrorActionPreference = "Stop"

# ── Authentication ──
Write-Host "🔑 Authenticating..." -ForegroundColor Cyan
$token = (Get-AzAccessToken -ResourceUrl "https://analysis.windows.net/powerbi/api").Token
$headers = @{ Authorization = "Bearer $token"; "Content-Type" = "application/json" }
$apiBase = "https://api.powerbi.com/v1.0/myorg"

# ── Step 1: Get current report info ──
Write-Host "`n📊 Current report binding:" -ForegroundColor Cyan
$report = Invoke-RestMethod `
    -Uri "$apiBase/groups/$WorkspaceId/reports/$ReportId" `
    -Headers $headers

Write-Host "  Report:  $($report.name)"
Write-Host "  Current dataset: $($report.datasetId)"
Write-Host "  Target dataset:  $TargetDatasetId"

if ($report.datasetId -eq $TargetDatasetId) {
    Write-Host "`n✅ Report is already bound to the target dataset." -ForegroundColor Green
    exit 0
}

# ── Step 2: Rebind ──
Write-Host "`n🔄 Rebinding report..." -ForegroundColor Cyan
$body = @{ datasetId = $TargetDatasetId } | ConvertTo-Json

try {
    Invoke-RestMethod `
        -Uri "$apiBase/groups/$WorkspaceId/reports/$ReportId/Rebind" `
        -Method POST `
        -Body $body `
        -Headers $headers

    Write-Host "✅ Report rebound successfully!" -ForegroundColor Green
    Write-Host "  Layout preserved: Yes"
    Write-Host "  New dataset: $TargetDatasetId"
}
catch {
    Write-Host "❌ Rebind failed: $($_.Exception.Message)" -ForegroundColor Red
    throw
}
