# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "03f9285a-2b8f-4daa-9873-549325797fb3",
# META       "default_lakehouse_name": "Dev_Lakehouse",
# META       "default_lakehouse_workspace_id": "6cfe7d37-f6e1-4461-8c01-6c70d981e257",
# META       "known_lakehouses": [
# META         {
# META           "id": "03f9285a-2b8f-4daa-9873-549325797fb3"
# META         }
# META       ]
# META     }
# META   }
# META }

# MARKDOWN ********************

# # 04 — Gold Layer Analytics
# **Generated by GitHub Copilot Agent Mode**
# # MAGIC
# Builds business-ready Gold tables from Silver data for direct Power BI consumption.
# Completes the Bronze → Silver → Gold medallion architecture.
# # MAGIC
# **Gold tables created:**
# - `gold_regional_pnl` — Budget vs Actuals P&L by region and quarter
# - `gold_asset_utilization` — Fleet age, depreciation exposure, replacement planning
# - `gold_executive_scorecard` — One row per region with RAG status indicators

# CELL ********************

from pyspark.sql.functions import (
    col, lit, when, sum as spark_sum, avg, count, max as spark_max,
    min as spark_min, round as spark_round, current_timestamp,
    concat, datediff, current_date
)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## Gold: Regional P&L Summary
# Budget vs Actuals rolled up by region and quarter — the CFO's view.

# CELL ********************

silver_budgets = spark.table("silver_regional_budgets")

gold_pnl = (
    silver_budgets
    .groupBy("region", "fiscal_year", "quarter", "currency")
    .agg(
        spark_round(spark_sum("budget_amount"), 0).alias("total_budget"),
        spark_round(spark_sum("actual_amount"), 0).alias("total_actuals"),
        spark_round(spark_sum("forecast_amount"), 0).alias("total_forecast"),
        spark_round(spark_sum("variance"), 0).alias("total_variance"),
        spark_round(avg("variance_pct"), 1).alias("avg_variance_pct"),
        spark_round(avg("forecast_accuracy_pct"), 1).alias("avg_forecast_accuracy"),
        count("*").alias("department_count"),
    )
    .withColumn(
        "rag_status",
        when(col("avg_variance_pct") > 10, "RED")
        .when(col("avg_variance_pct") > 5, "AMBER")
        .when(col("avg_variance_pct") < -10, "RED")
        .when(col("avg_variance_pct") < -5, "AMBER")
        .otherwise("GREEN")
    )
    .withColumn(
        "budget_health",
        when(col("rag_status") == "GREEN", "On Track")
        .when(col("rag_status") == "AMBER", "Needs Attention")
        .otherwise("Action Required")
    )
    .withColumn("_gold_refreshed_at", current_timestamp())
    .orderBy("region", "fiscal_year", "quarter")
)

gold_pnl.write.format("delta").mode("overwrite").saveAsTable("gold_regional_pnl")
row_count = spark.table("gold_regional_pnl").count()
print(f"✅ gold_regional_pnl: {row_count} rows")
gold_pnl.show(truncate=False)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## Gold: Asset Utilization Dashboard
# Fleet health per region — what needs replacing, what's costing the most.

# CELL ********************

silver_assets = spark.table("silver_fixed_assets")

gold_assets = (
    silver_assets
    .groupBy("region", "category")
    .agg(
        count("*").alias("asset_count"),
        spark_round(spark_sum("acquisition_cost"), 0).alias("total_acquisition_cost"),
        spark_round(spark_sum("net_book_value"), 0).alias("total_net_book_value"),
        spark_round(spark_sum("accumulated_depreciation"), 0).alias("total_depreciation"),
        spark_round(avg("age_years"), 1).alias("avg_age_years"),
        spark_round(avg("useful_life_years"), 1).alias("avg_useful_life"),
        spark_round(spark_max("age_years"), 1).alias("oldest_asset_years"),
    )
    .withColumn(
        "depreciation_pct",
        spark_round(col("total_depreciation") / col("total_acquisition_cost") * 100, 1)
    )
    .withColumn(
        "remaining_life_pct",
        spark_round((1 - col("avg_age_years") / col("avg_useful_life")) * 100, 1)
    )
    .withColumn(
        "replacement_urgency",
        when(col("remaining_life_pct") < 20, "URGENT")
        .when(col("remaining_life_pct") < 40, "PLAN")
        .otherwise("OK")
    )
    .withColumn(
        "fleet_health",
        when(col("replacement_urgency") == "URGENT", "🔴 Replace within 1-2 years")
        .when(col("replacement_urgency") == "PLAN", "🟡 Plan replacement")
        .otherwise("🟢 Healthy")
    )
    .withColumn("_gold_refreshed_at", current_timestamp())
    .orderBy("region", "category")
)

gold_assets.write.format("delta").mode("overwrite").saveAsTable("gold_asset_utilization")
row_count = spark.table("gold_asset_utilization").count()
print(f"✅ gold_asset_utilization: {row_count} rows")
gold_assets.show(truncate=False)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## Gold: Executive KPI Scorecard
# One row per region — the board-level view. Power BI connects directly to this table.

# CELL ********************

# Regional budget performance
budget_kpis = (
    spark.table("gold_regional_pnl")
    .groupBy("region")
    .agg(
        spark_round(spark_sum("total_budget"), 0).alias("annual_budget"),
        spark_round(spark_sum("total_actuals"), 0).alias("annual_actuals"),
        spark_round(avg("avg_variance_pct"), 1).alias("budget_variance_pct"),
        spark_round(avg("avg_forecast_accuracy"), 1).alias("forecast_accuracy_pct"),
    )
)

# Regional asset health
asset_kpis = (
    spark.table("gold_asset_utilization")
    .groupBy("region")
    .agg(
        spark_sum("asset_count").alias("total_assets"),
        spark_round(spark_sum("total_acquisition_cost"), 0).alias("total_fleet_value"),
        spark_round(spark_sum("total_net_book_value"), 0).alias("total_book_value"),
        spark_round(avg("depreciation_pct"), 1).alias("avg_depreciation_pct"),
        spark_round(avg("remaining_life_pct"), 1).alias("avg_remaining_life_pct"),
    )
)

# Regional headcount
headcount_kpis = (
    spark.table("silver_employee_regions")
    .groupBy("region")
    .agg(
        count("*").alias("headcount"),
        spark_sum(when(col("is_manager") == True, 1).otherwise(0)).alias("manager_count"),
    )
)

# Join everything into one executive scorecard
gold_scorecard = (
    budget_kpis
    .join(asset_kpis, "region", "left")
    .join(headcount_kpis, "region", "left")
    .withColumn(
        "overall_rag",
        when(
            (col("budget_variance_pct") > 10) | (col("avg_remaining_life_pct") < 20),
            "RED"
        )
        .when(
            (col("budget_variance_pct") > 5) | (col("avg_remaining_life_pct") < 40),
            "AMBER"
        )
        .otherwise("GREEN")
    )
    .withColumn(
        "executive_summary",
        when(col("overall_rag") == "RED",
             concat(lit("⚠️ "), col("region"), lit(": Requires immediate attention")))
        .when(col("overall_rag") == "AMBER",
             concat(lit("📋 "), col("region"), lit(": Monitor closely")))
        .otherwise(
             concat(lit("✅ "), col("region"), lit(": Operating within targets")))
    )
    .withColumn("_gold_refreshed_at", current_timestamp())
    .orderBy("region")
)

gold_scorecard.write.format("delta").mode("overwrite").saveAsTable("gold_executive_scorecard")
row_count = spark.table("gold_executive_scorecard").count()
print(f"✅ gold_executive_scorecard: {row_count} rows")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## Final Summary — Gold Layer Complete

# CELL ********************

print("=" * 70)
print("  GOLD LAYER — MEDALLION ARCHITECTURE COMPLETE")
print("=" * 70)
print()

gold_tables = ["gold_regional_pnl", "gold_asset_utilization", "gold_executive_scorecard"]
for t in gold_tables:
    df = spark.table(t)
    print(f"  📊 {t}: {df.count()} rows, {len(df.columns)} columns")

print()
print("  These tables are ready for Power BI DirectLake connection.")
print("  No import needed — Power BI reads directly from OneLake.")
print("=" * 70)

# Show the executive scorecard — this is what the board sees
print("\n🏢 Executive Scorecard Preview:")
spark.table("gold_executive_scorecard").select(
    "region", "annual_budget", "annual_actuals", "budget_variance_pct",
    "total_assets", "total_fleet_value", "avg_remaining_life_pct",
    "headcount", "overall_rag", "executive_summary"
).show(truncate=False)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
